global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - compute_metrics.rules
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['172.20.0.1:9101']
      # - targets: ['180.149.251.120:9101']
      # - targets: ['180.149.250.158:9100', '180.149.250.158:9101', '180.149.251.161:9100', '180.149.251.162:9100', 'localhost:9090']
      # for the internal docker tests, the following tragets line applies.
      # Please adjust according to your IP address.
      # targets: ['<host-ip>:9100', localhost:9090]
  - job_name: testProvider
    static_configs:
      - targets: ['localhost:8001']
